# fly.toml app configuration file generated for botzela-discord on 2023-04-30T14:13:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "botzela-discord"
primary_region = "ams"

